import os, re, json, glob
from PIL import Image, ImageOps

SRC = r"C:\Users\Admin\Desktop\fastbuilt\Example photos for the website"
OUT = r"C:\Users\Admin\Desktop\fastbuilt\web\public\images\workforce"
LIST_JS = r"C:\Users\Admin\Desktop\fastbuilt\web\src\lib\workforcePhotos.js"
MAX = 900        # longest side px
Q = 82           # webp quality

os.makedirs(OUT, exist_ok=True)
# clear old
for f in glob.glob(os.path.join(OUT, "*.webp")):
    os.remove(f)

files = []
for ext in ("*.jpg", "*.jpeg", "*.png", "*.JPG", "*.JPEG", "*.PNG"):
    files += glob.glob(os.path.join(SRC, "**", ext), recursive=True)
files = sorted(set(files))

def parse(fname):
    base = os.path.splitext(os.path.basename(fname))[0].strip()
    m = re.match(r"^\d+[_\s]+(.*)$", base)          # leading number like "01_" => has a name
    if m:
        rest = m.group(1).strip()
        parts = [p for p in re.split(r"[_\s]+", rest) if p]
        if not parts:
            return None
        name = parts[0]
        role = " ".join(parts[1:]).strip() if len(parts) > 1 else "On-site Team"
        return name, role
    return None                                     # no real name (DSC etc.) -> skip

entries = []
n = 0
for f in files:
    p = parse(f)
    if not p:
        print("  skip (no name):", os.path.basename(f))
        continue
    try:
        im = Image.open(f)
        im = ImageOps.exif_transpose(im)            # honour camera rotation
        im = im.convert("RGB")
        im.thumbnail((MAX, MAX), Image.LANCZOS)
        n += 1
        out_name = f"w{n:03d}.webp"
        im.save(os.path.join(OUT, out_name), "WEBP", quality=Q, method=6)
        name, role = p
        entries.append({"name": name, "role": role, "image": f"/images/workforce/{out_name}"})
        print(f"  {os.path.basename(f)} -> {out_name}  ({name} / {role})")
    except Exception as e:
        print("  SKIP", f, e)

js = ("// AUTO-GENERATED by _convert_photos.py — bundled workforce photos (WebP).\n"
      "export const WORKFORCE_PHOTOS = " + json.dumps(entries, ensure_ascii=False, indent=2) + "\n")
with open(LIST_JS, "w", encoding="utf-8") as fh:
    fh.write(js)

# total size
total = sum(os.path.getsize(os.path.join(OUT, x)) for x in os.listdir(OUT))
print(f"\n{len(entries)} webp images, total {total/1024/1024:.2f} MB -> {OUT}")
print("list ->", LIST_JS)
