// AUTO-GENERATED by _convert_photos.py — bundled workforce photos (WebP).
export const WORKFORCE_PHOTOS = [
  {
    "name": "Madhav",
    "role": "Foreman",
    "image": "/images/workforce/w001.webp"
  },
  {
    "name": "Ramakant",
    "role": "Carpentar",
    "image": "/images/workforce/w002.webp"
  },
  {
    "name": "Rajkumar",
    "role": "Carpentar",
    "image": "/images/workforce/w003.webp"
  },
  {
    "name": "Jaysankar",
    "role": "Barbender",
    "image": "/images/workforce/w004.webp"
  },
  {
    "name": "Madam",
    "role": "Barbender",
    "image": "/images/workforce/w005.webp"
  },
  {
    "name": "Jeetram",
    "role": "Carpentar",
    "image": "/images/workforce/w006.webp"
  },
  {
    "name": "Ganesh",
    "role": "Carpentar",
    "image": "/images/workforce/w007.webp"
  },
  {
    "name": "Mauryaji",
    "role": "Carpentar",
    "image": "/images/workforce/w008.webp"
  },
  {
    "name": "Rajaram",
    "role": "Carpentar",
    "image": "/images/workforce/w009.webp"
  },
  {
    "name": "Devram",
    "role": "Carpentar",
    "image": "/images/workforce/w010.webp"
  },
  {
    "name": "Mahandar",
    "role": "On-site Team",
    "image": "/images/workforce/w011.webp"
  },
  {
    "name": "Vishvjeet",
    "role": "Helper",
    "image": "/images/workforce/w012.webp"
  },
  {
    "name": "Akash",
    "role": "Helper",
    "image": "/images/workforce/w013.webp"
  },
  {
    "name": "Gorhari",
    "role": "Carpentar",
    "image": "/images/workforce/w014.webp"
  },
  {
    "name": "Ripondas",
    "role": "Carpentar",
    "image": "/images/workforce/w015.webp"
  }
]
